CREATE TABLE "screen" (
  "screen_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "screen_name" varchar,
  "screen_ds" varchar,
  "filename" varchar,
  "rec_ins_ts" timestamp
);

CREATE TABLE "dq_rules" (
  "rule_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rule_name" varchar,
  "rule_ds" varchar,
  "screen_id" integer,
  "rule_type" varchar,
  "rule_query" varchar,
  "rec_ins_ts" timestamp
);

CREATE TABLE "dq_row_alert_log" (
  "row_alert_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rule_id" integer,
  "screen_id" integer,
  "rule_ds" varchar,
  "error_record_count" integer,
  "rec_ins_ts" timestamp
);

CREATE TABLE "dq_profile_alert_log" (
  "profile_alert_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rule_id" integer,
  "screen_id" integer,
  "rule_ds" varchar,
  "error_record_count" integer,
  "rec_ins_ts" timestamp
);

CREATE TABLE "dq_scr_run_log" (
  "scr_run_key" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "screen_id" integer,
  "start_time" timestamp,
  "end_time" timestamp,
  "status" varchar,
  "error_msg" varchar,
  "rec_ins_ts" timestamp
);

ALTER TABLE "dq_rules" ADD FOREIGN KEY ("screen_id") REFERENCES "screen" ("screen_id");

ALTER TABLE "dq_row_alert_log" ADD FOREIGN KEY ("screen_id") REFERENCES "screen" ("screen_id");

ALTER TABLE "dq_row_alert_log" ADD FOREIGN KEY ("rule_id") REFERENCES "dq_rules" ("rule_id");

ALTER TABLE "dq_scr_run_log" ADD FOREIGN KEY ("screen_id") REFERENCES "screen" ("screen_id");

ALTER TABLE "dq_profile_alert_log" ADD FOREIGN KEY ("screen_id") REFERENCES "screen" ("screen_id");

ALTER TABLE "dq_profile_alert_log" ADD FOREIGN KEY ("rule_id") REFERENCES "dq_rules" ("rule_id");
